name: sizes
on:
  pull_request:
    branches:
      - main
jobs:
  size_compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: compile
          pattern: "./dist/**/*.js"
          exclude: "./example/dist/*"
