name: sizes
on:
  pull_request:
    branches:
      - main
jobs:
  size_compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: compile
          pattern: "./dist/**/*.js"
          exclude: "./example/dist/*"
